# Generated by Django 5.1.4 on 2025-03-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('PR', 'Professeur'), ('MC', 'Maître de conférences'), ('DR', 'Docteur'), ('ATER', "Attaché temporaire d'enseignement et de recherche"), ('VAC', 'Vacataire')], max_length=10)),
                ('specialite', models.CharField(max_length=100)),
                ('etablissement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=255)),
                ('niveau', models.CharField(choices=[('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2)),
                ('maitre_memoire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants_encadres', to='api.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='api.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('type_groupe', models.CharField(editable=False, max_length=10)),
                ('etudiants', models.ManyToManyField(related_name='groupes', to='api.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Binome',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.groupe',),
        ),
        migrations.CreateModel(
            name='Monome',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.groupe',),
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('numero_pv', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proces_verbal', to='api.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='RoleJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRES', 'Président'), ('EXAM', 'Examinateur'), ('RAPP', 'Rapporteur')], max_length=4)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_soutenance', models.DateField()),
                ('heure_soutenance', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('resultat', models.CharField(blank=True, max_length=100, null=True)),
                ('mention', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True)),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='api.groupe')),
                ('membres_jury', models.ManyToManyField(related_name='soutenances', through='api.RoleJury', to='api.enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='rolejury',
            name='soutenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_jury', to='api.soutenance'),
        ),
        migrations.AlterUniqueTogether(
            name='rolejury',
            unique_together={('enseignant', 'soutenance')},
        ),
    ]
