# Generated by Django 5.1.6 on 2025-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidat_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenements',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
