# Generated by Django 5.1.4 on 2025-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enseignant_filiere_etudiant_groupe_binome_monome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filiere',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
