# Generated by Django 5.1.4 on 2025-03-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_etudiant_filiere_alter_etudiant_maitre_memoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='maitre_memoire',
        ),
    ]
