# Generated by Django 5.1.4 on 2025-05-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidat_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'RESPONSABLE'), ('organisateur', 'ORGANISATEUR'), ('surveillant', 'SURVEILLANT')], default='organisateur', max_length=50, verbose_name="Type d'utilisateur"),
        ),
    ]
