# Generated by Django 5.1.4 on 2025-03-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_etudiant_maitre_memoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='maitre_memoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_encadres', to='api.enseignant'),
        ),
    ]
