# Generated by Django 5.1.4 on 2025-05-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='membres_jury',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='resultat',
        ),
        migrations.AddField(
            model_name='soutenance',
            name='binome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenances', to='api.binome'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='jury',
            field=models.ManyToManyField(related_name='soutenances_jury', through='api.RoleJury', to='api.enseignant'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='monome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenances', to='api.monome'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('reporte', 'Reporté')], default='planifie', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='rolejury',
            name='soutenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_membres', to='api.soutenance'),
        ),
        migrations.AlterField(
            model_name='rolejury',
            name='type',
            field=models.CharField(choices=[('PRES', 'Président'), ('EXAM', 'Examinateur'), ('RAPP', 'Rapporteur'), ('DR', 'Directeur')], max_length=4),
        ),
    ]
