# Generated by Django 5.1.4 on 2025-05-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_soutenance_groupe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='directeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rolejury',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_jury', to='api.enseignant'),
        ),
        migrations.AlterField(
            model_name='rolejury',
            name='type',
            field=models.CharField(choices=[('PRES', 'Président'), ('EXAM', 'Examinateur'), ('RAPP', 'Rapporteur')], max_length=4),
        ),
    ]
