# Generated by Django 5.1.4 on 2025-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_etudiant_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(choices=[('L3', 'Licence 3'), ('M2', 'Master 2')], max_length=2),
        ),
    ]
