# Generated by Django 5.1.4 on 2025-03-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_etudiant_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='maitre_memoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_encadres', to='api.enseignant'),
        ),
    ]
