# Generated by Django 5.1.4 on 2025-03-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_filiere_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau',
        ),
    ]
