# Generated by Django 5.1.4 on 2025-03-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_binome_etudiant1_remove_binome_etudiant2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binome',
            name='programmation',
            field=models.CharField(choices=[('est programmé', 'Est programmé'), ('pas encore programmé', 'Pas encore programmé'), ('refus', 'Refus')], default='Pas encore programmé', max_length=50),
        ),
    ]
