# Generated by Django 5.1.4 on 2025-03-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_binome_programmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binome',
            options={'verbose_name': 'Binôme', 'verbose_name_plural': 'Binômes'},
        ),
        migrations.AlterField(
            model_name='binome',
            name='etudiants',
            field=models.ManyToManyField(related_name='binomes', to='api.etudiant', verbose_name='Étudiants du binôme'),
        ),
        migrations.AlterField(
            model_name='binome',
            name='maitre_memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binomes_encadres', to='api.enseignant', verbose_name='Maître de mémoire'),
        ),
        migrations.AlterField(
            model_name='binome',
            name='programmation',
            field=models.CharField(choices=[('est programmé', 'Est programmé'), ('pas encore programmé', 'Pas encore programmé'), ('refus', 'Refus')], default='pas encore programmé', max_length=50, verbose_name='Statut de programmation'),
        ),
        migrations.AlterField(
            model_name='binome',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Thème de recherche'),
        ),
    ]
