# Generated by Django 5.1.4 on 2025-03-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_binome_options_alter_binome_etudiants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binome',
            name='programmation',
            field=models.CharField(choices=[('est programmé', 'Est programmé'), ('Non programmé', 'Non programmé'), ('refus', 'Refus')], default='pas encore programmé', max_length=50, verbose_name='Statut de programmation'),
        ),
    ]
