# Generated by Django 5.1.4 on 2025-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_binome_programmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binome',
            name='programmation',
            field=models.CharField(choices=[('est programmé', 'Est programmé'), ('non programmé', 'Non programmé'), ('refus', 'Refus')], max_length=50, verbose_name='Statut de programmation'),
        ),
    ]
