# Generated by Django 5.1.4 on 2025-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_binome_programmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monome',
            name='programmation',
            field=models.CharField(choices=[('est programmé', 'Est programmé'), ('non programmé', 'Non programmé'), ('refus', 'Refus')], default='non programmé', max_length=50, verbose_name='Status de programmation'),
        ),
        migrations.AlterField(
            model_name='binome',
            name='programmation',
            field=models.CharField(choices=[('est programmé', 'Est programmé'), ('non programmé', 'Non programmé'), ('refus', 'Refus')], default='non programmé', max_length=50, verbose_name='Statut de programmation'),
        ),
    ]
